name: Test and Build
on:
  pull_request:
    branches: "development"
jobs:
  run-debug-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.1.0

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'

  run-ui-tests:
    name: Android Tests
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: ./gradlew connectedAndroidTest

      - name: Upload Android Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: android-test-reports
          path: '**/build/reports/androidTests/'


  build_job:
   name: Building the APK
   runs-on: ubuntu-latest
   continue-on-error: true
   steps:
     - name: Checkout
       uses: actions/checkout@v3.1.0
     - name: Restore Cache
       uses: actions/cache@v3
       with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

     - name: Change wrapper permissions
       run: chmod +x ./gradlew

     - name: Assemble Debug
       run: ./gradlew assembleDebug

     - name: Upload APK
       uses: actions/upload-artifact@v3
       with:
        name: apk
        path: app/build/outputs/apk/debug/**.apk